from pathlib import Path
import numpy as np, pandas as pd

BASE = Path(__file__).resolve().parent.parent
RES, MAT = BASE/"results", BASE/"data"/"matrices"

V   = ['lat', 'old', 'corr', 'corrpacu', 'collapse', 'restricted']
LBL = {'lat': 'lat (primary)', 'old': 'old (as published)', 'corr': 'corr',
       'corrpacu': 'corrpacu', 'collapse': 'collapse', 'restricted': 'restricted'}


DEEP = ['RNN', 'LSTM', 'GRU', 'BiLSTM', 'BiGRU', 'CNN', 'CNN-k23', 'CNN-LSTM']


SRC = {
    ('ICU', 'lat'): 'icu_feature_matrix_v2_lat.csv',
    ('ICU', 'old'): 'icu_feature_matrix_v2.csv',
    ('ICU', 'corr'): 'icu_feature_matrix_v2.csv',
    ('ICU', 'corrpacu'): 'icu_feature_matrix_v2.csv',
    ('ICU', 'collapse'): 'icu_feature_matrix_v2.csv',
    ('ICU', 'restricted'): 'icu_feature_matrix_restricted.csv',
    ('SW', 'lat'): 'sw_feature_matrix_v2_lat.csv',
    ('SW', 'old'): 'sw_feature_matrix_v2.csv',
    ('SW', 'corr'): 'sw_feature_matrix_v2_corr.csv',
    ('SW', 'corrpacu'): 'sw_feature_matrix_v2_corrpacu.csv',
    ('SW', 'collapse'): 'sw_feature_matrix_v2_collapse.csv',
    ('SW', 'restricted'): 'sw_feature_matrix_restricted.csv',
}
LABEL_COL = {'ICU': 'icu_left_shift', 'SW': 'sw_left_shift'}


def prevalence(cohort, variant):
    """Positive rate over the whole modelling matrix, computed not remembered."""
    df = pd.read_csv(MAT/SRC[(cohort, variant)], usecols=[LABEL_COL[cohort]])
    return df[LABEL_COL[cohort]].mean()


RATE = {(c, v): prevalence(c, v) for c in ('ICU', 'SW') for v in V}

ml  = {v: pd.read_csv(RES/f"ml_results_{v}.csv")  for v in V}
mlp = {v: pd.read_csv(RES/f"mlp_results_{v}.csv") for v in V}
dl  = pd.read_csv(RES/"all_results_long.csv")
alj1 = pd.read_csv(RES/"aljebreen_table1_reference.csv")

deep = dl[dl.Model.isin(DEEP)]
g = deep.groupby(['Variant', 'Cohort', 'Condition', 'Model'])['AUROC'].agg(['mean', 'std', 'count'])


def clf(v, cohort, model, condition):
    """Mean AUROC over seeds for a classical model. Never .iloc[0] — RF is stochastic."""
    src = mlp[v] if model == 'MLP' else ml[v]
    q = src[(src.Cohort == cohort) & (src.Condition == condition)]
    if model != 'MLP':
        q = q[q.Model == model]
    return q.AUROC.mean()


def has_clf(v, cohort):
    """corr, corrpacu and collapse relabel the SW cohort only — no ICU runs exist."""
    return ((ml[v].Cohort == cohort).any())


O = []; W = O.append
W("# Dissertation results tables\n")
W("*Generated by `python/generate_tables.py` from the result files. Do not edit by hand — rerun the script.*")
W(f"*{len(dl):,} runs in `all_results_long.csv` ({len(deep):,} deep, {len(dl)-len(deep):,} classical/MLP), "
  f"5 seeds (42, 1, 2, 3, 4), {deep.Train_Time_s.sum()/3600:.2f} GPU-hours on the deep models.*")
W(f"*Primary label variant: `lat`. Positive rate in the modelling matrix: "
  f"SW {RATE[('SW','lat')]:.2%}, ICU {RATE[('ICU','lat')]:.2%}.*")
W("*The `restricted` cohort is a different admission set with its own partition and its own "
  "`split_id`. Its rows are NOT comparable to the canonical variants and must be read separately.*\n")

W("## Table 0 — cohort sizes and positive rates\n")
W("| Variant | ICU n | ICU positive rate | SW n | SW positive rate |")
W("|---|---|---|---|---|")
for v in V:
    ni = sum(1 for _ in open(MAT/SRC[('ICU', v)], encoding='utf-8')) - 1
    ns = sum(1 for _ in open(MAT/SRC[('SW', v)], encoding='utf-8')) - 1
    W(f"| {LBL[v]} | {ni:,} | {RATE[('ICU',v)]:.2%} | {ns:,} | {RATE[('SW',v)]:.2%} |")

W("\n## Table 1 — ICU baseline replication, No Process features\n")
W("| Model | Aljebreen et al. Table 1 | This study (`lat`) | Δ | This study (`old`) | Δ |")
W("|---|---|---|---|---|---|")
for m in ['LR', 'GB', 'RF', 'KNN']:
    a = alj1.query("Model==@m and Cohort=='ICU'").AUROC.iloc[0]
    l = clf('lat', 'ICU', m, 'No Process')
    o = clf('old', 'ICU', m, 'No Process')
    W(f"| {m} | {a:.2f} | {l:.4f} | {l-a:+.4f} | {o:.4f} | {o-a:+.4f} |")

W("\n## Table 2 — classical ML and MLP, primary label (`lat`), AUROC\n")
W("| Cohort | Model | No Process | With Process | With BoW |")
W("|---|---|---|---|---|")
for co in ['ICU', 'SW']:
    for m in ['LR', 'RF', 'GB', 'KNN']:
        W(f"| {co} | {m} | {clf('lat',co,m,'No Process'):.4f} | "
          f"{clf('lat',co,m,'With Process'):.4f} | {clf('lat',co,m,'With BoW'):.4f} |")
    W(f"| {co} | MLP | {clf('lat',co,'MLP','No Process'):.4f} | "
      f"{clf('lat',co,'MLP','With Process'):.4f} | — |")

W("\n## Table 3 — deep architectures, primary label (`lat`), mean ± sd over 5 seeds\n")
W("| Model | ICU Seq-Only | ICU Seq+Tab | SW Seq-Only | SW Seq+Tab |")
W("|---|---|---|---|---|")
for m in DEEP:
    c = [f"{g.loc[('lat',co,cond,m)]['mean']:.4f} ± {g.loc[('lat',co,cond,m)]['std']:.4f}"
         for co in ['ICU', 'SW'] for cond in ['Sequence Only', 'Sequence + Tabular']]
    W(f"| {m} | {c[0]} | {c[1]} | {c[2]} | {c[3]} |")

W("\n## Table 4 — classical ML vs every neural model, identical test patients\n")
W("| Label | Cohort | GB | RF | MLP | Best deep (Seq+Tab) | Deep range, 8 models | GB − best deep |")
W("|---|---|---|---|---|---|---|---|")
for v in V:
    for co in ['ICU', 'SW']:
        if (v, co, 'Sequence + Tabular') not in g.index or not has_clf(v, co):
            continue
        gb = clf(v, co, 'GB', 'With Process')
        rf = clf(v, co, 'RF', 'With Process')
        mp = clf(v, co, 'MLP', 'With Process')
        x = g.loc[(v, co, 'Sequence + Tabular')]['mean']
        W(f"| {LBL[v]} | {co} | **{gb:.4f}** | {rf:.4f} | {mp:.4f} | {x.idxmax()} {x.max():.4f} | "
          f"{x.min():.4f}–{x.max():.4f} | **{gb-x.max():+.4f}** |")

W("\n## Table 5 — architecture spread vs seed noise (deep models only)\n")
W("| Label | Cohort | Condition | Architecture spread | Mean seed sd | Verdict |")
W("|---|---|---|---|---|---|")
for k, x in g.groupby(level=[0, 1, 2]):
    a = x['mean'].max() - x['mean'].min(); s = x['std'].mean()
    W(f"| {LBL[k[0]]} | {k[1]} | {k[2]} | {a:.4f} | {s:.4f} | "
      f"{'indistinguishable' if a < 2*s else 'detectable'} |")

W("\n## Table 6 — label-sensitivity: process-feature gain, SW cohort\n")
W("| Model | " + " | ".join(f"{LBL[v]}<br>{RATE[('SW',v)]:.2%}" for v in V) + " |")
W("|---" * (len(V)+1) + "|")
for m in ['LR', 'RF', 'GB', 'KNN']:
    row = [m] + [f"{clf(v,'SW',m,'With Process')-clf(v,'SW',m,'No Process'):+.4f}" for v in V]
    W("| " + " | ".join(row) + " |")

W("\n## Table 7 — BoW gain over With Process (all labels, both cohorts)\n")
W("| Label | Cohort | LR | RF | GB | KNN | max |")
W("|---|---|---|---|---|---|---|")
for v in V:
    for co in ['ICU', 'SW']:
        if not has_clf(v, co):
            continue
        gains = [clf(v, co, m, 'With BoW') - clf(v, co, m, 'With Process')
                 for m in ['LR', 'RF', 'GB', 'KNN']]
        W(f"| {LBL[v]} | {co} | " + " | ".join(f"{x:+.4f}" for x in gains)
          + f" | **{max(gains):+.4f}** |")

W("\n## Table 8 — contribution of tabular features to the deep models\n")
W("| Label | Cohort | Mean AUROC gain, Sequence-Only → Sequence+Tabular |")
W("|---|---|---|")
p = g['mean'].reset_index().pivot_table(index=['Variant', 'Cohort', 'Model'], columns='Condition', values='mean')
for k, x in (p['Sequence + Tabular'] - p['Sequence Only']).groupby(level=[0, 1]):
    W(f"| {LBL[k[0]]} | {k[1]} | **+{x.mean():.4f}** (range {x.min():.4f}–{x.max():.4f}) |")

cells = len(g.groupby(level=[0, 1, 2]))
W(f"\n## Table 9 — architecture mean rank across all {cells} cells\n")
W("| Architecture | Mean rank (1 = best of 8) | Best | Worst |")
W("|---|---|---|---|")
ranks = {}
for k, x in g.groupby(level=[0, 1, 2]):
    for (v, co, cond, m), r in x['mean'].rank(ascending=False).items():
        ranks.setdefault(m, []).append(r)
for m, r in sorted(ranks.items(), key=lambda kv: np.mean(kv[1])):
    W(f"| {m} | {np.mean(r):.2f} | {int(min(r))} | {int(max(r))} |")

W("\n## Table 10 — GB vs the best neural model, paired by seed\n")
W("*95 % t-interval on the per-seed difference, n = 5. GB is deterministic, so the "
  "spread is the neural model's. An interval excluding zero licenses the word 'beats'.*\n")
W("| Cohort | Label | GB | Best neural | Δ | 95 % CI | Verdict |")
W("|---|---|---|---|---|---|---|")
for co in ['ICU', 'SW']:
    for v in V:
        if (v, co, 'Sequence + Tabular') not in g.index or not has_clf(v, co):
            continue
        gbs = (dl[(dl.Model == 'GB') & (dl.Cohort == co) & (dl.Variant == v)
                  & (dl.Condition == 'With Process')].set_index('Seed').AUROC.sort_index())
        cands = {}
        for m in DEEP:
            s = dl[(dl.Model == m) & (dl.Cohort == co) & (dl.Variant == v)
                   & (dl.Condition == 'Sequence + Tabular')].set_index('Seed').AUROC.sort_index()
            if len(s):
                cands[m] = s
        s = dl[(dl.Model == 'MLP') & (dl.Cohort == co) & (dl.Variant == v)
               & (dl.Condition == 'With Process')].set_index('Seed').AUROC.sort_index()
        if len(s):
            cands['MLP'] = s
        best = max(cands, key=lambda m: cands[m].mean())
        d = (gbs - cands[best]).dropna()
        h = 2.776 * d.std(ddof=1) / np.sqrt(len(d))
        lo, hi = d.mean() - h, d.mean() + h
        verdict = 'GB beats' if lo > 0 else ('neural beats' if hi < 0 else 'tie')
        W(f"| {co} | {LBL[v]} | {gbs.mean():.4f} | {best} {cands[best].mean():.4f} | "
          f"**{d.mean():+.4f}** | [{lo:+.4f}, {hi:+.4f}] | {verdict} |")

(RES/"dissertation_tables.md").write_text("\n".join(O), encoding="utf-8", newline="\n")
print(f"wrote results/dissertation_tables.md ({len(O)} lines, 11 tables, {len(V)} variants)")
